services:
  postgres:
    image: postgres:17.6
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./dev/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql